### ISSUE TITLE
Adopt shields.io standard

### ISSUE THREAD

**Issue by valencik** [buildkite/build-status-badge-themes#1]
It would be great if Buildkite badges could adopt/support the [Shields.io](https://shields.io/) standard. When using a Buildkite badge alongside other badges the difference is noticeable.

<img width="281" alt="buildkite badge too short" src="https://user-images.githubusercontent.com/5440389/31099015-988f6f54-a792-11e7-9fe0-4ab00bc7fdbd.png">

**Comment by ticky** [comment]
We were actually following the Shields.io style before the current version was established! 😜

I’m looking into getting us updated, though ☺️

Do you know if Shields.io offer any guidance on implementation or suggestions on what to use? Doesn’t seem like there’s any good Ruby implementation available. Seems silly given their suggestion to "Tell your favorite badge service to use it!”.

**Comment by ticky** [comment]
We just shipped this. Let us know if you have any issues! :)
