### ISSUE TITLE
Label information in JSON

### ISSUE THREAD

**Issue by raulriera** [buildkite/build-status-badge-themes#2]
It would be nice if doing this 

```
$ curl https://badge.buildkite.com/3826789cf8890b426057e6fe1c4e683bdf04fa24d498885489.json?branch=master
```

Would return the pipeline name in the payload

```
{"name": "Name in Buildkite", "status": "passing"}
```

**Comment by toolmantim** [comment]
We can add that for you! For the name, are you wanting the pipeline name?

**Comment by raulriera** [comment]
Exactly, that would be amazing. 🙌

**Comment by raulriera** [comment]
Although it may not be needed if this is merged https://github.com/badges/shields/pull/1657, since shields.io supports just passing a name with `?label=custom-name`

**Comment by toolmantim** [comment]
I'll leave it for the minute then. Let me know how you go!

**Comment by raulriera** [comment]
I'll close the issue since the label would have been used there anyway. Thanks!
